import unittest
from sbol.partshop import PartShop
from sbol.document import Document
import os
from sbol.sbolerror import SBOLError


if 'username' in os.environ:
    username = os.environ['username']
else:
    username = None
if 'password' in os.environ:
    password = os.environ['password']
else:
    password = None


class TestPartShop(unittest.TestCase):
    def test_pull_00(self):
        """Based on tutorial: https://pysbol2.readthedocs.io/en/latest/repositories.html"""
        doc = Document()
        igem = PartShop('https://synbiohub.org')
        igem.pull('https://synbiohub.org/public/igem/BBa_R0010/1', doc)
        print(doc)
        for obj in doc:
            print(obj)
        self.assertEqual(3, len(doc))

    def test_pull_01(self):
        """Based on tutorial: https://pysbol2.readthedocs.io/en/latest/repositories.html"""
        doc = Document()
        igem = PartShop('https://synbiohub.org/public/igem')
        igem.pull('BBa_B0032', doc)
        igem.pull('BBa_E0040', doc)
        igem.pull('BBa_B0012', doc)
        print(doc)
        for obj in doc:
            print(obj)
        self.assertEqual(7, len(doc))

    def test_pull_02(self):
        doc = Document()
        ps = PartShop('https://synbiohub.utah.edu/public/RepressionModel')
        ps.pull('CRPb_characterization_Circuit', doc)
        print(doc)
        for obj in doc:
            print(obj)
        self.assertEqual(31, len(doc))

    def test_login(self):
        # NOTE: Add /login because login pages may be different depending on what site you're accessing
        igem = PartShop('https://synbiohub.org')
        response = igem.login('johndoe@example.org', 'test')
        self.assertEqual(response.status_code, 200)

    def test_login_bad(self):
        with self.assertRaises(SBOLError):
            igem = PartShop('https://synbiohub.org')
            igem.login('johndoe@example.org', 'test1')

    def test_submit_00(self):
        doc = Document()
        doc.displayId = 'test_collection'
        doc.name = 'test collection'
        doc.description = 'a test collection automatically generated by the SBOL client library'
        ps = PartShop('https://hub-staging.sd2e.org')
        ps.login(username, password)
        response = ps.submit(doc, overwrite=1)
        self.assertEqual(response.status_code, 200)
