#!/bin/bash

# Run unit tests
echo "Running unit tests..."
python3 -m unittest discover -s test
if [ $? != 0 ]; then
   cat <<\EOF
Error: There were failing unit tests.

Please make sure all unit tests are passing before making
a commit.
EOF
    exit 1
fi 

# Run style checker
MAX_VIOLATIONS=23
echo "Checking style..."
pycodestyle sbol2 test examples > style.txt
result=$(cat style.txt | wc -l)
if [ "$result" -gt $MAX_VIOLATIONS ]; then
    cat <<EOF
Error: Too many style violations. Found $result violations and
expected fewer than $MAX_VIOLATIONS. Please make sure there are fewer
than $MAX_VIOLATIONS style violations before making a commit.

See style.txt for all style issues.
EOF
    exit 1
else
    echo "Found $result style violations"
fi
